server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework

spring:
  security:
    saml2:
      relyingparty:
        registration:
          keycloak:
            entity-id: "spring-boot-saml-client"
            signing:
              credentials:
                - private-key-location: "classpath:credentials/saml-private.key"
                  certificate-location: "classpath:credentials/saml-public.crt"