server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework

logging:
  level:
    org.springframework.security: DEBUG
spring:
  security:
    saml2:
      relyingparty:
        registration:
          keycloak:
            entity-id: "{baseUrl}/saml2/service-provider-metadata/{registrationId}"
            signing:
              credentials:
                - private-key-location: "classpath:credentials/saml-private.key"
                  certificate-location: "classpath:credentials/saml-public.crt"
            assertingparty:
              metadata-uri: ${KEYCLOAK_URL:http://keycloak:8080}/realms/osu/protocol/saml/descriptor